# Generated by Django 4.2 on 2023-04-20 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phong_gddt', models.CharField(max_length=255)),
                ('truong_tieu_hoc', models.CharField(max_length=255)),
                ('lop', models.CharField(max_length=255)),
                ('ho_va_ten', models.CharField(max_length=255)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3)),
                ('ngay_sinh', models.DateField()),
                ('noi_sinh', models.CharField(max_length=255)),
                ('dan_toc', models.CharField(max_length=255)),
                ('noi_thuong_tru_so_nha', models.CharField(max_length=255)),
                ('noi_thuong_tru_to', models.CharField(max_length=255)),
                ('noi_thuong_tru_phuong', models.CharField(max_length=255)),
                ('noi_thuong_tru_quan_huyen', models.CharField(max_length=255)),
                ('noi_thuong_tru_tinh', models.CharField(max_length=255)),
                ('sdt', models.CharField(max_length=20)),
                ('ma_hoc_sinh', models.CharField(max_length=10)),
                ('ma_dinh_danh', models.CharField(max_length=12)),
                ('khen_thuong', models.JSONField(blank=True)),
                ('ket_qua_kiem_tra', models.JSONField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
