# Generated by Django 4.2 on 2023-04-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ket_qua_kiem_tra',
        ),
        migrations.RemoveField(
            model_name='application',
            name='khen_thuong',
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_1_tieng_viet',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_1_toan',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_2_tieng_viet',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_2_toan',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_3_tieng_anh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_3_tieng_viet',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_3_toan',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_4_khoa_hoc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_4_su_dia',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_4_tieng_anh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_4_tieng_viet',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_4_toan',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_5_khoa_hoc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_5_su_dia',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_5_tieng_anh',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_5_tieng_viet',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ket_qua_5_toan',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='khen_thuong_1',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='khen_thuong_2',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='khen_thuong_3',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='khen_thuong_4',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='khen_thuong_5',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
