# Generated by Django 4.2 on 2023-04-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinh', '0002_remove_application_ket_qua_kiem_tra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ngay_nop',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
