# Generated by Django 4.2 on 2023-04-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinh', '0003_application_ngay_nop'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tong_diem',
            field=models.FloatField(null=True),
        ),
    ]
