# Generated by Django 4.2 on 2023-04-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinh', '0005_alter_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ma_hoc_sinh',
        ),
    ]
