# Generated by Django 4.2 on 2023-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinh', '0006_remove_application_ma_hoc_sinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='anh_3x4',
            field=models.ImageField(null=True, upload_to='anh_3x4'),
        ),
    ]
