# Generated by Django 4.2 on 2023-05-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinh', '0008_application_ma_ho_so'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='ma_hoc_sinh',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
