# Generated by Django 4.2 on 2023-05-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinh', '0009_remove_application_user_application_ma_hoc_sinh'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['ma_ho_so'], name='tuyensinh_a_ma_ho_s_9dd4b1_idx'),
        ),
    ]
