# Generated by Django 4.2 on 2023-05-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinh', '0010_application_tuyensinh_a_ma_ho_s_9dd4b1_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='anh_3x4',
        ),
    ]
