# Generated by Django 4.2 on 2023-05-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuyensinh', '0013_alter_application_noi_thuong_tru_so_nha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tong_diem_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tong_diem_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tong_diem_3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tong_diem_4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tong_diem_5',
            field=models.FloatField(null=True),
        ),
    ]
